version: '3.8'
services:
  devcontainer:
    image: apache/nifi:2.0.0-M2
    volumes:
      - ../..:/workspaces:cached
    ports:
      - 8443:8443
    entrypoint: tail -f /dev/null
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: nifi+langchain

  db:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data: 